apiVersion: v1
kind: Service
metadata:
  name: matchengine
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "matchengine.labels" . | nindent 4 }}
    app: matchengine
spec:
  type: ClusterIP
  selector:
    app: matchengine
  ports:
    - name: http
      port: 80
      targetPort: http
