apiVersion: v1
kind: Service
metadata:
  name: interviewhandoff
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "interviewhandoff.labels" . | nindent 4 }}
    app: interviewhandoff
spec:
  type: ClusterIP
  selector:
    app: interviewhandoff
  ports:
    - name: http
      port: 80
      targetPort: http
